-- Tabla de Laboratorios Clínicos
CREATE TABLE laboratorios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  fecha_examen DATE NOT NULL,
  glucosa NUMERIC,
  colesterol_total NUMERIC,
  hdl NUMERIC,
  ldl NUMERIC,
  trigliceridos NUMERIC,
  insulina NUMERIC,
  notas TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Políticas RLS
ALTER TABLE laboratorios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver los laboratorios de sus pacientes" 
ON laboratorios FOR SELECT 
TO authenticated 
USING (
  paciente_id IN (
    SELECT id FROM profiles WHERE tenant_id = (SELECT tenant_id FROM profiles WHERE id = auth.uid())
  )
);

CREATE POLICY "Los usuarios pueden insertar laboratorios" 
ON laboratorios FOR INSERT 
TO authenticated 
WITH CHECK (
  paciente_id IN (
    SELECT id FROM profiles WHERE tenant_id = (SELECT tenant_id FROM profiles WHERE id = auth.uid())
  )
);

CREATE POLICY "Los usuarios pueden actualizar laboratorios" 
ON laboratorios FOR UPDATE 
TO authenticated 
USING (
  paciente_id IN (
    SELECT id FROM profiles WHERE tenant_id = (SELECT tenant_id FROM profiles WHERE id = auth.uid())
  )
);

CREATE POLICY "Los usuarios pueden eliminar laboratorios" 
ON laboratorios FOR DELETE 
TO authenticated 
USING (
  paciente_id IN (
    SELECT id FROM profiles WHERE tenant_id = (SELECT tenant_id FROM profiles WHERE id = auth.uid())
  )
);
